### ISSUE TITLE
Near range LODs don't render, no OceanRenderer.Instance.CollisionProvider data

### ISSUE THREAD

**Issue by karearea** [crest-ocean/crest#322]
Near range LODs don't render, no OceanRenderer.Instance.CollisionProvider data, no LOD Data visible on the GUI. 

Building and running the threeboats scene causes the boat to fall through where the water would be expected.

In my own project, OceanRenderer.Instance.CollisionProvider.SampleHeight causes a crash.

The log shows this error repeatedly:

`Out of bounds index
Crest.OceanWaveSpectrum:GetAmplitude(Single, Single)
Crest.ShapeGerstnerBatched:UpdateAmplitudes()
Crest.ShapeGerstnerBatched:UpdateWaveData()
Crest.ShapeGerstnerBatched:Update()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

IndexOutOfRangeException: Index was outside the bounds of the array.
  at Crest.ShapeGerstnerBatched.ReportMaxDisplacement () [0x00000] in <00000000000000000000000000000000>:0 `

Unity version is 2019.2.1f1. Crest LWRP V. 2

Build: Mac OSX Standalone. No problems in editor, or on windows builds.

Mac OS Mojave 10.14.6 (18G87)

GPU: Radeon Pro 455 2 GB
Intel HD Graphics 530 1536 MB

To reproduce, set up Unity LWRP according to docs (utilising the shadows system). Build for OSX standalone with threeboats.unity as the only scene.

[Player.log](https://github.com/crest-ocean/crest/files/3513851/Player.log)

<img width="1680" alt="Screen Shot 2019-08-19 at 13 17 39" src="https://user-images.githubusercontent.com/16930004/63233619-52606a00-c285-11e9-91d0-07b6320c80ad.png">

**Comment by huwb** [comment]
Apologies this was due to legacy data that wasn't upgraded alongside the wave improvements recently.

I have fixed this on the github latest, but i just realised you reported this on lwrp, so reopening. As a fix on lwrp, could you please select each of these in the editor and press save which should upgrade the data:

![image](https://user-images.githubusercontent.com/939901/63246044-a3f2ff80-c259-11e9-92f4-65dfbde4094e.png)

**Comment by huwb** [comment]
I also opened PR #323 to improve messaging here to make the errors less confusing.

**Comment by karearea** [comment]
Hi,

I've upgraded all of those, and in fact rebuilt the appropriate data for my own game. The boat test level still doesn't show any close-in water, however the log is now free of the error (and suspiciously short)- I've attached it below.

[Player.log](https://github.com/crest-ocean/crest/files/3514969/Player.log)

In my own game the water suffers from the same issue, but the log does have an error, presumably the script execution order is incorrect?

<img width="516" alt="Screen Shot 2019-08-19 at 21 01 20" src="https://user-images.githubusercontent.com/16930004/63252788-9757c100-c2c4-11e9-8deb-6b53bd87ac67.png">
 
RenderData validation failed: _frame of data (704) != expected (705), which may indicate some update functions are being called out of order, or script execution order is broken.
Crest.LodDataMgrPersistent:ValidateSourceData(Boolean)
Crest.LodDataMgr:SubmitDraws(Int32, CommandBuffer)
Crest.LodDataMgrSeaFloorDepth:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:Build(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:LateUpdate()

Worth mentioning again that there is no issue at all in the Editor, on both PC and Mac, or on PC Standalone builds.

**Comment by karearea** [comment]
Ah, correction, that execution order error is only thrown if I exit the scene, and disappears when the ocean object is destroyed. Here's a log where I exit the game straight from the scene with the broken water rendering:

[Player.log](https://github.com/crest-ocean/crest/files/3515007/Player.log)

**Comment by karearea** [comment]
It looks like turning off 'Create dynamic wave sim' on the Ocean Renderer fixes the ocean rendering in the build, so there's something going on in that direction..

**Comment by huwb** [comment]
Ok thats a good lead.

Perhaps the sim gets a large timestep near the beginning. Could you try limit it by replacing this line:

`const float dt = _SimDeltaTime;`

with:

`const float dt = min(_SimDeltaTime, 0.0);`

That should stop any dynamic waves updating at all. You might see some green accumulating into the dynamic waves buffer, but everything visually should appear like theres only animated waves, not dynamic.

If that works could you try setting the max delta time to something more reasonable, like this:

`const float dt = min(_SimDeltaTime, 1/30.0);`

And let me know what you get?

Thanks!

**Comment by karearea** [comment]
Hi Huw,

Neither of those changes to UpdateDynWaves had any effect, unfortunately- the visual outcome was still of a missing near-range ocean surface, and no height sampling on the boats.

I've also tried rebuilding the library and forcing the Mac graphics API to Metal-only in the player settings.

**Comment by huwb** [comment]
Hmm. Could you try turning off the boats and the ripple (if its in that scene) to make sure they're not killing it?

It might also be that the textures have bad initial values, not sure if we're still clearing them, I'll check later

**Comment by karearea** [comment]
Hi Huw,

Turning off all those items had no effect

**Comment by huwb** [comment]
Thanks. New test..

Could you add these two lines

            TextureArrayHelpers.ClearToBlack(_targets);
            TextureArrayHelpers.ClearToBlack(_sources);

to LodDataMgrPersistent.InitData() , so like this:

![image](https://user-images.githubusercontent.com/939901/63413055-dd11a800-c3f0-11e9-83bb-ae33316c8df4.png)

**Comment by karearea** [comment]
Hi, it looks like that has fixed all the above issues. Thanks!

**Comment by huwb** [comment]
Excuse me while i have a quick 'HOW THE HECK DID THAT EVER WORK???' moment. ok now i'll prepare a PR

**Comment by huwb** [comment]
Resolved in Crest LWRP 2.1
